#Makefile
#Devon DiIanni
#October 4th, 2019

PROJ = SLinkedList
CXX = gcc
SRC = Node.c SList.c main.c

mySLinkedList: ${SRC} 
	${CXX} ${SRC} -o slinkedlist

run:
	./slinkedlist
clean:
	rm * slinkedlist